from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import psycopg

from .diff import DiffKind, compute_diff
from .introspect import introspect_db
from .parser import parse_directory

_LAYER_PREFIX_RE = re.compile(r"^\d+_?")

# Matches the `tables`/`views`/`scalar_functions`/`table_functions` object-type
# subfolders documented in docs/database-layout.md.
SUBFOLDER = {
    "table": "tables",
    "view": "views",
    "scalar_function": "scalar_functions",
    "table_function": "table_functions",
}


@dataclass
class MissingObject:
    object_type: str  # "table" | "view" | "scalar_function" | "table_function"
    schema: str
    name: str

    @property
    def qualified_name(self) -> str:
        return f"{self.schema}.{self.name}"


def layer_folder_for(scripts_dir: Path, schema: str) -> Path:
    """Map a schema name to its existing layer directory under scripts_dir,
    matched by stripping each top-level folder's leading sort number (e.g.
    "1_reference_data" -> "reference_data"). Falls back to scripts_dir/schema
    if no existing folder matches."""
    if scripts_dir.is_dir():
        for entry in scripts_dir.iterdir():
            if not entry.is_dir() or entry.name in ("migrations", "_migration_scripts"):
                continue
            if _LAYER_PREFIX_RE.sub("", entry.name).lower() == schema.lower():
                return entry
    return scripts_dir / schema


def find_missing_objects(scripts_dir: Path, conninfo: str) -> list[MissingObject]:
    """Tables, views, and functions that exist in the live database but
    aren't tracked as .sql files under scripts_dir."""
    scripts = parse_directory(scripts_dir)
    db = introspect_db(conninfo)
    diffs = compute_diff(scripts, db, report_extra_db=True)

    missing: list[MissingObject] = []
    with psycopg.connect(conninfo) as conn:
        for d in diffs:
            if d.kind != DiffKind.MISSING_IN_SCRIPTS or d.object_type not in ("table", "view", "function"):
                continue
            schema, name = d.object_name.split(".", 1)
            object_type = d.object_type
            if object_type == "function":
                object_type = "table_function" if _returns_set(conn, schema, name) else "scalar_function"
            missing.append(MissingObject(object_type, schema, name))
    return missing


def _returns_set(conn: Any, schema: str, name: str) -> bool:
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT p.proretset
            FROM pg_catalog.pg_proc p
            JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace
            WHERE n.nspname = %s AND p.proname = %s AND p.prokind = 'f'
            ORDER BY p.oid LIMIT 1
            """,
            (schema, name),
        )
        row = cur.fetchone()
        return bool(row and row[0])


def reconstruct_ddl(conn: Any, obj: MissingObject) -> str:
    """Reverse-engineer the DDL for a missing object from pg_catalog."""
    if obj.object_type == "table":
        return _table_ddl(conn, obj.schema, obj.name)
    if obj.object_type == "view":
        return _view_ddl(conn, obj.schema, obj.name)
    return _function_ddl(conn, obj.schema, obj.name)


def _table_ddl(conn: Any, schema: str, table: str) -> str:
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT c.oid
            FROM pg_catalog.pg_class c
            JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
            WHERE n.nspname = %s AND c.relname = %s AND c.relkind = 'r'
            """,
            (schema, table),
        )
        row = cur.fetchone()
        if not row:
            raise ValueError(f"Table {schema}.{table} not found in pg_catalog")
        oid = row[0]

        cur.execute(
            """
            SELECT
                a.attname,
                pg_catalog.format_type(a.atttypid, a.atttypmod),
                a.attnotnull,
                a.attidentity,
                a.attgenerated,
                CASE
                    WHEN a.attidentity = 'a' THEN 'GENERATED ALWAYS AS IDENTITY'
                    WHEN a.attidentity = 'd' THEN 'GENERATED BY DEFAULT AS IDENTITY'
                    WHEN a.attgenerated = 's' THEN
                        'GENERATED ALWAYS AS (' || pg_catalog.pg_get_expr(ad.adbin, ad.adrelid) || ') STORED'
                    WHEN ad.adbin IS NOT NULL THEN
                        'DEFAULT ' || pg_catalog.pg_get_expr(ad.adbin, ad.adrelid)
                    ELSE NULL
                END
            FROM pg_catalog.pg_attribute a
            LEFT JOIN pg_catalog.pg_attrdef ad
                ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
            WHERE a.attrelid = %s AND a.attnum > 0 AND NOT a.attisdropped
            ORDER BY a.attnum
            """,
            (oid,),
        )
        columns = cur.fetchall()

        cur.execute(
            """
            SELECT conname, pg_catalog.pg_get_constraintdef(oid, true)
            FROM pg_catalog.pg_constraint
            WHERE conrelid = %s
            ORDER BY contype, conname
            """,
            (oid,),
        )
        constraints = cur.fetchall()

        cur.execute(
            """
            SELECT indexname, indexdef
            FROM pg_indexes
            WHERE schemaname = %s AND tablename = %s
              AND indexname NOT IN (
                  SELECT conname FROM pg_catalog.pg_constraint WHERE conrelid = %s
              )
            ORDER BY indexname
            """,
            (schema, table, oid),
        )
        indexes = cur.fetchall()

    col_defs: list[str] = []
    for attname, data_type, not_null, identity, _generated, extra in columns:
        col_def = f"{attname} {data_type}"
        if not_null and not identity:
            col_def += " NOT NULL"
        if extra:
            col_def += f" {extra}"
        col_defs.append(col_def)

    for conname, condef in constraints:
        col_defs.append(f"CONSTRAINT {conname} {condef}")

    ddl = f"CREATE TABLE IF NOT EXISTS {schema}.{table} (\n"
    ddl += ",\n".join(f"    {c}" for c in col_defs)
    ddl += "\n);\n"

    for _, indexdef in indexes:
        indexdef = re.sub(r"^CREATE INDEX\b", "CREATE INDEX IF NOT EXISTS", indexdef)
        indexdef = re.sub(r"^CREATE UNIQUE INDEX\b", "CREATE UNIQUE INDEX IF NOT EXISTS", indexdef)
        ddl += f"\n{indexdef};\n"

    return ddl


def _view_ddl(conn: Any, schema: str, name: str) -> str:
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT pg_get_viewdef(c.oid, true)
            FROM pg_catalog.pg_class c
            JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
            WHERE n.nspname = %s AND c.relname = %s AND c.relkind = 'v'
            """,
            (schema, name),
        )
        row = cur.fetchone()
        if not row or row[0] is None:
            raise ValueError(f"View {schema}.{name} not found in pg_catalog")
        return f"CREATE OR REPLACE VIEW {schema}.{name} AS\n{row[0].rstrip()};\n"


def _function_ddl(conn: Any, schema: str, name: str) -> str:
    """Fetch a function's DDL via pg_get_functiondef.

    If the function is overloaded, this uses the lowest-oid (oldest) match —
    good enough to seed a file; resolve manually if there's more than one."""
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT p.oid
            FROM pg_catalog.pg_proc p
            JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace
            WHERE n.nspname = %s AND p.proname = %s AND p.prokind = 'f'
            ORDER BY p.oid LIMIT 1
            """,
            (schema, name),
        )
        row = cur.fetchone()
        if not row:
            raise ValueError(f"Function {schema}.{name} not found in pg_catalog")

        cur.execute("SELECT pg_catalog.pg_get_functiondef(%s)", (row[0],))
        ddl_row = cur.fetchone()
        if not ddl_row or ddl_row[0] is None:
            raise ValueError(f"Could not reconstruct DDL for function {schema}.{name}")
        return ddl_row[0].rstrip() + ";\n"
